bump the fe shell
* push all calls to end of script
* export and use IRON_FUNCS
* define and export IRON_VERSION

If a .fe declares a requirement on a specific IRON_VERSION via
IRON_VERSION_REQUIRED, this is checked during iron_init.

diff --git a/bin/fe b/bin/fe
--- a/bin/fe
+++ b/bin/fe
@@ -28,42 +28,53 @@
 #
 IRON_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 IRON_PATH="$IRON_DIR"/"$(basename "$0")"
-export IRON_DIR IRON_PATH
+IRON_FUNCS="$IRON_DIR/iron-funcs"
+IRON_VERSION="0.9"
+source "$IRON_FUNCS" || exit 1
+export IRON_DIR IRON_PATH IRON_FUNCS
 
 # IRON_PROMPT: fe shell prompt.
 IRON_PROMPT=${IRON_PROMPT:="iron (?|#|#?|!)> "}
 
-function find_fesh {
+function find_dotfe {
     cur_path="$(pwd)"
     while [ "$cur_path" != '/' ]; do
-        if [ -r "$cur_path/.fe.sh" ]; then
+        if [ -r "$cur_path/.fe" ]; then
             IRON_FESH_DIR="$cur_path"
             export IRON_FESH_DIR
             return 0
         fi
         cur_path="$(readlink -f "$cur_path/..")"
-        echo "$cur_path"
     done
     IRON_FESH_DIR=""
     export IRON_FESH_DIR
     return 1
 }
 
-find_fesh
-fail_msg="fatal: Not an Iron tree, no '.fe.sh' found"
-source "${IRON_FESH_DIR:?$fail_msg}/.fe.sh" || exit 1
-fail_msg="fatal: Missing IRON_SCRIPTS, set it in \"$IRON_FESH_DIR/.fe.sh\""
-IRON_SCRIPTS="${IRON_SCRIPTS:?$fail_msg}"
-export IRON_SCRIPTS
-# Execute from IRON_SCRIPTS
-cd "$IRON_SCRIPTS" || exit 1
+function iron_init {
+    find_dotfe
+    fail_msg="fatal: Not an Iron tree, no '.fe' found"
+    source "${IRON_FESH_DIR:?$fail_msg}/.fe" || exit 1
+    fail_msg="fatal: Missing IRON_SCRIPTS, set it in \"$IRON_FESH_DIR/.fe\""
+    IRON_SCRIPTS="${IRON_SCRIPTS:?$fail_msg}"
+    export IRON_SCRIPTS
+
+    # Check version required against current if needed.
+    if [ -n "$IRON_VERSION_REQUIRED" ]; then
+        if [ "$IRON_VERSION_REQUIRED" != "$IRON_VERSION" ]; then
+            fail_msg="fatal: Required IRON_VERSION is $IRON_VERSION_REQUIRED, "
+            fail_msg+="this is version $IRON_VERSION"
+            echo "$fail_msg" >&2
+            exit 1
+        fi
+    fi
+}
 
 function header {
     echo "iron: the fe shell"
     echo "https://github.com/formwork-io/iron"
     echo "This is free software with ABSOLUTELY NO WARRANTY."
 }
-header
 
 # Defines the SCRIPTS array for use everywhere else.
 function redefine_scripts {
@@ -168,8 +179,6 @@ function help {
 function reset_prompt {
     PROMPT="\n${IRON_PROMPT}"
 }
-
-reset_prompt
 
 # Drain the stdin buffer.
 function drain_stdin {
@@ -429,7 +438,11 @@ function args() {
     echo "Processing arguments before entering the shell."
 }
 
+iron_init
+header
+reset_prompt
 redefine_scripts
+
 if [ $# -gt 0 ]; then
     args "$@"
 elif [ ! -z "$IRON_SUBMENU_ARGS" ]; then
@@ -441,4 +454,3 @@ else
     echo "Try 'help' for more information."
 fi
 loop
-
